# This is a configuration file for the MLPBase regression model
model:
    type: mlp
    variant: base
    input_dim: 10
    hidden_dims: [64]
    output_dim: 1
    activation: relu
    dropout: 0.1

task:
    type: regression
    dataset: synthetic
    loss: mse
    metrics: [mae, rmse]

dataset:
    name: synthetic
    batch_size: 32
    num_workers: 4
    shuffle: true

training:
    epochs: 100
    batch_size: 64
    learning_rate: 0.001
    optimizer: sgd
    weight_decay: 0.0
    beta: [0.9, 0.999]

lora:
    enabled: false
    rank: 8
    steps: 50
    alpha: 16
    dropout: 0.1

# 저장 및 분석 설정
save:
  dir: results/mlpbase_regression/
  save_model: true
  save_taus: true
  plot_results: true

analysis:
  analyze_tau: true
  fit_exponential: false