model:
    name: vit_tiny_patch16_224
    type: image
    pretrained: true

data:
    name: CIFAR10
    task: classification
    output_dim: 10
    batch_size: 128

finetuning:
    method: lora
    epochs: 30
    lr: 1e-3
    optimizer: sgd
    momentum: 0.0
    early_stop: true
    early_stop_patience: 3

lora:
    enabled: true
    rank: 8
    steps: 50
    alpha: 16
    dropout: 0.1

save:
    enabled: true
    every: 10

logging:
    use_wandb: true
    wandb_project: my_exp_proj
    run_name: vit_cifar10_run01
    dir: logs
