model:
    name: vit_tiny_patch16_224
    type: image
    pretrained: true

data:
    name: CIFAR10
    task: classification
    output_dim: 10
    batch_size: 128

finetuning:
    method: lora
    epochs: 10
    lr: 1.e-3
    optimizer: sgd
    momentum: 0.0

lora:
    rank: 8
    alpha: 16
    dropout: 0.1

early_stop:
    enabled: true
    patience: 3

save:
    enabled: true
    every: 10

logging:
    enabled: true
    use_wandb: true
