model:
    name: vit_tiny_patch16_224
    type: image
    pretrained: true

data:
    name: CIFAR10
    task: classification
    output_dim: 10
    batch_size: 128

finetuning:
    method: full
    epochs: 20
    lr: 1.e-5
    optimizer: adam

early_stop:
    enabled: false
    patience: 6

save:
    enabled: true
    every: 30

logging:
    enabled: true
    use_wandb: true

analyze:
    modes: epoch
    indices: 5
    alpha_grid: [0.001, 0.01, 0.1, 0.5, 1]
