model:
    name: vit_tiny_patch16_224
    type: image
    pretrained: true

data:
    name: CIFAR10
    task: classification
    output_dim: 10
    batch_size: 128

finetuning:
    method: full
    epochs: 20
    lr: 1.e-4
    optimizer: adam

early_stop:
    enabled: false
    patience: 6

save:
    enabled: true
    every: 30

logging:
    enabled: true
    use_wandb: true
