# Basic settings
seed: 42

# Model settings
model_id: openai/clip-vit-base-patch32

# Data settings
data:
    name: tanganke/eurosat
    image_column_name: image
    label_column_name: label

    split_strategy: auto_split
    validation_split_size: 0.2

    batch_size: 128
    num_workers: 4

# Finetuning settings (kept the same for a direct comparison)
finetuning:
    method: lora
    optimizer: sgd
    epochs: 40
    lr: 1.e-2
    momentum: 0.9

    # LoRA settings (kept even if method=full; simply unused)
    lora:
        r: 16
        lora_alpha: 32
        target_modules: [q_proj, v_proj]
        lora_dropout: 0.0
        bias: none

# Analysis & Save settings
analysis:
    save_tau_every_n_steps: 100
    num_monitoring_elements: 20
    num_analysis_elements: 50

# Logging settings
logging:
    enabled: true
    wandb: true
