exp:
    seed: 42

model:
    name: vit-b-32
    pretrained: laion2b_s34b_b79k

data:
    name: cifar10
    batch_size: 128

finetuning:
    method: lora
    optimizer: sgd
    epochs: 20
    lr: 1.e-3
    momentum: 0.0

save:
    enabled: true
    every: 100

logging:
    enabled: true
    use_wandb: true

analyze:
    modes: epoch
    indices: 6
    alpha_grid: [0.001, 0.01, 0.1, 0.5, 1]
